from setuptools import setup, find_packages

setup(
    name="inerd",
    version="0.1",
    author="Tobias Deusser",
    packages=find_packages(),
    install_requires=[
        "torch==2.0.0",
        "fluidml==0.3.1",
        "datasets",
        "tokenizers",
        "pytorch-lightning==2.0.3",
        "torch",
        "tqdm",
        "transformers==4.29.2",
        "wandb",
        "pyyaml",
        "rich",
        "numpy",
        "markdown",
        "torchmetrics",
        "pandas",
        "fsspec",
        "deepspeed==0.9.4",
        "chardet",
        # "bitsandbytes",
        "accelerate",
        "peft",
        "einops==0.6.1",
        "sentencepiece==0.1.99",
    ],
)
