# Base directory to store all task outputs
#base_dir: "/cluster/data/experiments/misusing_llms/conll2003_v1"
#base_dir: "/scratch/data/misusing_llms/conll2003_dev"
#base_dir: "/cluster/data/experiments/misusing_llms/conll2003_fsdp"
base_dir: "/cluster/data/experiments/misusing_llms/conll2003_debug"
seed: &seed 3141

###########
# Parsing #
###########

Parsing:
  dataset: "CoNLL-2003"
  path_to_data_folders: null
  dataset_name: "CoNLL-2003"
  debug_size: 12
  type_mapping:
    PER: "Person"
    LOC: "Location"
    ORG: "Organisation"
    MISC: "Miscellaneous"

################
# Tokenisation #
################

# models too large for one 32gb GPU:
# "bigscience/bloom-1b7"
# "facebook/opt-2.7b"

# models fitting on one 32gb GPU:
# "facebook/opt-1.3b"
# "bigscience/bloom-1b1"
# "EleutherAI/gpt-neo-1.3B"
# "bigscience/bloom-560m"

# models fitting on two 32gb GPUs with fsdp and cpu offloading:
# "bigscience/bloom-1b7"
# "facebook/opt-2.7b"

# models not fitting on four 32gb GPUs with fsdp and cpu offl oading:
# "bigscience/bloom-3b"

Tokenisation:
  tokeniser_name: &modelname "bigscience/bloom-1b1"
  special_tokens: null
  combine_token: "\n"


##################
# Model Training #
##################

## HF Trainer
#Training:
#  model_name: *modelname
#  combine_train_valid: false
#  validate_on_test_set: false
#  huggingface_trainer_params:
#    # see https://huggingface.co/docs/transformers/v4.28.1/en/main_classes/trainer#transformers.TrainingArguments
#    per_device_train_batch_size: 8
#    per_device_eval_batch_size: 8
#    num_train_epochs: 2
#    gradient_accumulation_steps: 1
#    learning_rate: 1.e-5
#    weight_decay: 0

Training:

  - seed: *seed

    wandb_logging: false
    tensorboard_logging: false
    csv_logging: true

    model_params:
      model_name: *modelname

    informed_generation: true

    training_params:
      optimiser:
        type_: 'adamW'
        lr: 1.e-5
        weight_decay: 0.01

#      lr_scheduler:
#        type_: 'lin_warmup'
#        interval: 'step'
#        lr_warmup: 0.1

      trainer:
        max_epochs: 10
        accumulate_grad_batches: 1 # [2, 4]  # 4
        gradient_clip_val: 1  # [1, 10]  # 10
        precision: 32
#        precision: 16
        val_check_interval: 1. # 0.25  # 1.

      callbacks:
        monitor_var: 'valid-ner_micro_f1'
        monitor_var_mode: 'max'
        apply_early_stopping: false
        patience: null
        save_top_k: 1

      metrics:
        nerf1: null
#        bleu:
#          n_gram: 4
#          smooth: false
#          weights: null

      data_loading:
        batch_size: 2
#        drop_last: false
        combine_train_valid: false
        validate_on_test_set: false