# Base directory to store all task outputs
#base_dir: "/cluster/data/experiments/misusing_llms/conll2003_v1"
base_dir: "/scratch/data/misusing_llms/conll2003_dev"
seed: &seed 3141

###########
# Parsing #
###########

Parsing:
  dataset: "CoNLL-2003"
  path_to_data_folders: null
  dataset_name: "CoNLL-2003"
  debug_size: 10
  type_mapping:
    PER: "Person"
    LOC: "Location"
    ORG: "Organisation"
    MISC: "Miscellaneous"

################
# Tokenisation #
################

Tokenisation:
  tokeniser_name: &modelname "facebook/opt-1.3b"
#  tokeniser_name: &modelname "bigscience/bloom-1b1"
  special_tokens: null
  combine_token: "\n"


##################
# Model Training #
##################

Training:

  - seed: *seed

    wandb_logging: true
    tensorboard_logging: false

    model_params:
      model_name: *modelname

    informed_generation: true

    training_params:
      optimiser:
        type_: 'adamW'
        lr: 1.e-5
        weight_decay: 0.01

      lr_scheduler:
        type_: 'lin_warmup'
        interval: 'step'
        lr_warmup: 0.1

      trainer:
        max_epochs: 20
        accumulate_grad_batches: 1 # [2, 4]  # 4
        gradient_clip_val: 1  # [1, 10]  # 10
        precision: 32  # 16
        amp_level: null
        val_check_interval: 1. # 0.25  # 1.

      callbacks:
        monitor_var: 'valid-ner_micro_f1'
        monitor_var_mode: 'max'
        apply_early_stopping: false
        patience: null
        save_top_k: 1

      metrics:
        nerf1: null
#        bleu:
#          n_gram: 4
#          smooth: false
#          weights: null

      data_loading:
        batch_size: 2
        drop_last: false
        combine_train_valid: false
        validate_on_test_set: false