# Base directory to store all task outputs
#base_dir: "/cluster/data/experiments/misusing_llms/conll2003_v1"
#base_dir: "/scratch/data/misusing_llms/conll2003_dev"
#base_dir: "/cluster/data/experiments/misusing_llms/conll2003_fsdp"
#base_dir: "/cluster/data/experiments/misusing_llms/conll2003_debug"
#base_dir: "/cluster/data/experiments/misusing_llms/conll2003_singlegpu"
#base_dir: "/cluster/data/experiments/misusing_llms/conll2003_v2"
base_dir: "/cephfs/experiments/inerd"  # lamarr
#base_dir: "/mnt/cephfs/users/deusser/experiments/inerd"  # lamarr
#base_dir: "/cluster/data/experiments/misusing_llms/pretraining" # wznbm
#base_dir : "/root/experiments/inerd"
seed: &seed 3141

###########
# Parsing #
###########

Parsing:
  dataset:
#    Species-800: null  # google drive down for this file?
#    FiNER-ORD: [false, true, true, true, true, true, true]
#    CoNLL++: [true, false, true, true, true, true, true]
#    Few-NERD: [true, true, false, true, true, true, true]
#    JNLPBA: [true, true, true, false, true, true, true]
#    WNUT-17: [true, true, true, true, false, true, true]
#    OntoNotes: [true, true, true, true, true, false, true]
#    NCBI-disease: [true, true, true, true, true, true, false]
    FiNER-ORD: true
    CoNLL++: true
    Few-NERD: true
    JNLPBA: true
    WNUT-17: true
    OntoNotes: true
    NCBI-disease: true
#      BC5CDR: "/cluster/data/ner/bc5cdr"
#    CoNLL-2003: false
#  dataset_name: "CoNLL-2003"
  debug_size: null
  type_mapping: true
  entity_separator_token: "<ES>"
  type_content_separator_token: "<TCS>"

################
# Tokenisation #
################

# models too large for one 32gb GPU:
# "bigscience/bloom-1b7"
# "facebook/opt-2.7b"

# models fitting on one 32gb GPU:
# "facebook/opt-1.3b"
# "bigscience/bloom-1b1"
# "EleutherAI/gpt-neo-1.3B"
# "bigscience/bloom-560m"
# "facebook/opt-125m"

# models fitting on one 32gb GPU with LORA:
# "togethercomputer/RedPajama-INCITE-Base-3B-v1"
# "togethercomputer/RedPajama-INCITE-Base-7B-v0.1"
# "tiiuae/falcon-7b"
# "bigscience/bloom-7b1"
# "facebook/opt-6.7b"
# llama: "/cluster/models/llama_weights/huggingface_converted/7B"
# llama: "/cephfs/llama_weights/huggingface_converted/7B"


# models fitting on two 32gb GPUs with fsdp and cpu offloading:
# "bigscience/bloom-1b7"
# "gpt2-xl"

# models not fitting on four 32gb GPUs with fsdp and cpu offloading:
# "bigscience/bloom-3b"
# "togethercomputer/RedPajama-INCITE-Base-3B-v1"
# "facebook/opt-2.7b"

# models fitting on four 32gb GPUs with fsdp, cpu offloading, and manual wrapping:
# "togethercomputer/RedPajama-INCITE-Base-3B-v1"

# models fitting on eight 32gb GPUs with fsdp, cpu offloading, and manual wrapping:
# "togethercomputer/RedPajama-INCITE-Base-7B-v0.1"

Tokenisation:
  tokeniser_name: &modelname "meta-llama/Llama-2-7b-hf"
#  tokeniser_name: &modelname "meta-llama/Llama-2-13b-hf"
#  tokeniser_name: &modelname "tiiuae/falcon-7b"
#  tokeniser_name: &modelname "togethercomputer/RedPajama-INCITE-7B-Base"
#  tokeniser_name: &modelname "gpt2-xl"
#  tokeniser_name: &modelname "/cephfs/llama_weights/huggingface_converted/7B"
#  tokeniser_name: &modelname "/cephfs/llama_weights/huggingface_converted/13B"
#  tokeniser_name: &modelname "/root/llama_weights/huggingface_converted/7B"
#  tokeniser_name: &modelname "/mnt/cephfs/users/deusser/llama_weights/huggingface_converted/7B"
#  tokeniser_name: &modelname "/cluster/public/llama_weights/huggingface_converted/7B"
#  tokeniser_name: &modelname "/mnt/cephfs/users/deusser/llama_weights/huggingface_converted/13B"
#  tokeniser_name: &modelname "/cephfs/llama_weights/huggingface_converted/13B"
#  tokeniser_name: &modelname "togethercomputer/RedPajama-INCITE-Base-3B-v1"
  llama: &llama false
  special_tokens: null
#  combine_token: "\n"
  combine_token: "<s>"
  add_leading_space: false

################
# Pre Training #
################

PreTraining:

  - seed: *seed

    wandb_logging: true
    csv_logging: true

    model_params:
      model_name: *modelname
      llama: *llama
      load_in_8bit: false
      lora: true
      lora_config:
        r: 8
        lora_alpha: 32
        lora_dropout: 0.1
        fan_in_fan_out: false

    generation_params:
      informed_generation: false
      num_beams: 1
      do_sample: false
      max_new_tokens: "adaptive"

    training_params:
      optimiser:
        type_: 'adamW'
        lr: 1.e-5
        weight_decay: 0.01

#      lr_scheduler:
#        type_: 'lin_warmup'
#        interval: 'step'
#        lr_warmup: 0.1

      trainer:
        max_epochs: 10
        accumulate_grad_batches: 64 # [2, 4]  # 4
        gradient_clip_val: 1  # [1, 10]  # 10
        precision: 32
#        precision: 16
        val_check_interval: 1. # 0.25  # 1.

      callbacks:
        monitor_var: 'valid-ner_micro_f1'
        monitor_var_mode: 'max'
        apply_early_stopping: true
        patience: 3
        save_top_k: 1

      data_loading:
        batch_size: 1
#        drop_last: false
        combine_train_valid: false
        validate_on_test_set: false
